import { registerWorker } from 'iii-browser-sdk';
import { readFileSync } from 'node:fs';
const FILE = '/home/robert/development/docx-audit-iii/副本景嘉微智能文档项目合同-需求和验收标准-0311(1)(1).docx';
const sdk = registerWorker('ws://localhost:49134', { workerName: 'final', invocationTimeoutMs: 600_000 });
await new Promise((r) => { let d=false; sdk.addConnectionStateListener(s=>{if(s==='connected'&&!d){d=true;r();}}); setTimeout(r,5000); });
const buf = readFileSync(FILE);
let binary = ''; const bytes = new Uint8Array(buf);
for (let i = 0; i < bytes.byteLength; i++) binary += String.fromCharCode(bytes[i]);
const b64 = btoa(binary);
const t0 = Date.now();
const r = await sdk.trigger({ function_id: 'docx::audit', payload: { content: b64, filename: '副本景嘉微.docx', use_llm: true, check_comments: false } });
console.log(`✅ 完成 ${Date.now()-t0}ms ok=${r.ok}`);
console.log('trace_id:', r.trace_id||'NONE');
console.log('summary:', JSON.stringify(r.summary));
const issues = r.issues||[];
console.log('issues:', issues.length);
const types = {};
for (const i of issues) types[i.issue_type||i.rule_id] = (types[i.issue_type||i.rule_id]||0)+1;
for (const [t,c] of Object.entries(types)) console.log(`   ${t}: ${c}`);
process.exit(0);
